# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-25 10:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171006_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sub_users',
            field=models.ManyToManyField(related_name='on_sub_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
