# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-25 11:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('likes_count', models.PositiveIntegerField()),
                ('title', models.CharField(default='', max_length=50)),
                ('photo', models.ImageField(upload_to='photo/<django.db.models.fields.related_descriptors.ForwardManyToOneDescriptor object at 0x7f6ccd213710>')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
