# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-25 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='photo/<django.db.models.fields.related_descriptors.ForwardManyToOneDescriptor object at 0x7f10ed847850>'),
        ),
    ]
