# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-25 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20170925_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to=post.models.user_directory_path),
        ),
    ]
