# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-25 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectevent',
            name='content_type',
        ),
        migrations.AddField(
            model_name='event',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='event',
            name='object_id',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.DeleteModel(
            name='ObjectEvent',
        ),
    ]
