# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-25 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20170925_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='event',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
